# Generated by Django 2.0.4 on 2018-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='assignee_notes',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='assignor_notes',
        ),
        migrations.AlterField(
            model_name='timelog',
            name='source_of_entry',
            field=models.CharField(blank=True, choices=[('T', 'Timer'), ('M', 'Manual'), ('A', 'Task Assignment')], max_length=1),
        ),
    ]
