# Generated by Django 2.0.4 on 2018-04-30 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180428_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budgeted_hrs',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
