# Generated by Django 2.0.4 on 2018-05-01 23:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180430_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='hrs_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='budgeted_hrs',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(error_messages={'unique': 'An engagement with this name already exists, the engagement name must  be unique'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='budgeted_hrs',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasktype', to='projects.MasterTaskCategory'),
        ),
    ]
