# Generated by Django 2.0.4 on 2018-05-02 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180501_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taskmodifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
