# Generated by Django 2.0.4 on 2018-05-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180501_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task_parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
